version: '3.9'
services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_USER=marcial
            - POSTGRES_PASSWORD=hola
            - POSTGRES_DB=store
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - 5432:5432
      
    